[package]
name = "ds3-map-viewer"
version.workspace = true
authors.workspace = true
edition = "2021"

[[bin]]
name = "ds3_map_viewer"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]
name = "libds3_map_viewer"

[dependencies]
tracing-subscriber = "0.3.17"
image = "0.24.9"
toml = "0.8.20"

libds3 = { path = "../lib/libds3" }

serde.workspace = true
hudhook.workspace = true
imgui.workspace = true
once_cell.workspace = true
windows.workspace = true

[build-dependencies]
embed-resource = "2.4.3"
