[package]
name = "ds3-map-probe"
version.workspace = true
authors.workspace = true
edition = "2021"

[[bin]]
name = "ds3_map_probe"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]
name = "libds3_map_probe"

[dependencies]
tracing-subscriber = "0.3.17"

libds3 = { path = "../lib/libds3" }

hudhook.workspace = true
imgui.workspace = true
once_cell.workspace = true
windows.workspace = true


