[package]
name = "darksoulsiii-practice-tool"
version.workspace = true
authors.workspace = true
edition = "2021"

[[bin]]
name = "jdsd_dsiii_practice_tool"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]
name = "libjdsd_dsiii_practice_tool"

[dependencies]
tracing-subscriber = "0.3.17"
image = "0.24.9"

libds3 = { path = "../lib/libds3" }

hudhook.workspace = true
imgui.workspace = true
once_cell.workspace = true
windows.workspace = true

[build-dependencies]
embed-resource = "2.4.3"
